version: 1.0.{build}  

image: Visual Studio 2019  

install:
 - cd C:\Tools\vcpkg
 - git pull
 - .\bootstrap-vcpkg.bat
 - cd %APPVEYOR_BUILD_FOLDER%
 - cd c:\tools\vcpkg
 - vcpkg integrate install
 #- .\vcpkg update
 - vcpkg install sfml
 #- vcpkg install libflac:x64-windows
 - vcpkg install sfml:x64-windows
 - vcpkg install tesseract
 #- vcpkg install sfml:x86-windows  
 - cd C:\projects\projekt
build_script:  
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ...  
  - cmake -H. -B_build  
  - cmake --build _build  
  - cmake --build _build --target main   
  - _build\Debug\main.exe  
  - echo "Testing main is done"  

 # - cd solver_application  
 # - cmake -H. -B_build  
 # - cmake --build _build  
 # - cmake --build _build --target solver  
 # - echo "Testing solver is done"  
#notifications:   
#- provider: Email   
# to:   
#  - 7986291@gmail.com  
#subject: kp (appveyor) 
#message: ะะบ! Build success! - ci.appveyor.com   
#on_build_success: true  
#on_build_failure: false     
#on_build_status_changed: false   
