version: 1.0.{build}  

image: Visual Studio 2019 
platform:
 # - x86
  - x64
configuration: Release

cache:
  - c:\Tools\vcpkg\installed
  #cache: c:\tools\vcpkg\installed\

init:
  - set TARGET_PLATFORM=
  - if "%platform%"=="x86" ( set TARGET_PLATFORM=Win32)
  - if "%platform%"=="x64" ( set TARGET_PLATFORM=x64)
  - if "%platform%"=="ARM" ( set TARGET_PLATFORM=ARM)
  - echo %TARGET_PLATFORM%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set "generator=Visual Studio 16 2019" && set "toolset=v142" )
  - echo %generator%
  - echo %toolset%

install:
# make sure the latest version of git is installed
  #- choco upgrade git ninja -y
  #- ninja --version
  - cmake --version
  #- cmake -DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  
  - cd C:\Tools\vcpkg
  #- vcpkg install sfml:x64-windows
  #- vcpkg install sfml:x86-windows
  #- vcpkg install tesseract:x64-windows
  #- vcpkg install tesseract:x86-windows
  - vcpkg integrate install
  - vcpkg list
# - git pull
# - .\bootstrap-vcpkg.bat
#- cd %APPVEYOR_BUILD_FOLDER%
# - cd c:\tools\vcpkg
 
 #- .\vcpkg update
 #- vcpkg install sfml
 #- vcpkg install libflac:x64-windows
 #- vcpkg install sfml:x64-windows
 #- vcpkg install tesseract:x64-windows
 #- vcpkg install sfml:x86-windows  
 # cd C:\projects\projekt
#build_script:  
# скрипт сборки проекта:
    #- cd C:\projects\projekt
    ##- mkdir build
    ##- cd build
    #работает на комп эта строка
   # - cmake -DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"

    #- cmake -H. -B_build -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    #- cmake --build _build  
    #- cmake --build _build --target main   
    #- _build\Debug\main.exe  
    #- echo "Testing main is done"  
build_script:
  - cd C:\projects\projekt
  - mkdir build
  - cd build
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  #- cmake -DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  #- cmake -Werror=dev -G "%generator%" -A %TARGET_PLATFORM% -T "%toolset%" -Denable-pkgconfig=0 -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DNO_GUI=1 ..
  - cmake --build .
  - .\Debug\main.exe


after_build:
  - 7z a fluidsynth-vcpkg-%platform%.zip %APPVEYOR_BUILD_FOLDER%\build\src\Release\*


artifacts:
  - path: build/projekt-vcpkg-%platform%.zip
    name: projekt

 
