version: 1.0.{build}  

image: Visual Studio 2019 
platform:
 # - x86
  - x64
configuration:
    # ... и в дебажной, и в релизной конфигурациях ...
    - Debug
    - Release

cache:
  - c:\Tools\vcpkg\installed
  #cache: c:\tools\vcpkg\installed\

init:
  - set TARGET_PLATFORM=
  - if "%platform%"=="x86" ( set TARGET_PLATFORM=Win32)
  - if "%platform%"=="x64" ( set TARGET_PLATFORM=x64)
  - if "%platform%"=="ARM" ( set TARGET_PLATFORM=ARM)
  - echo %TARGET_PLATFORM%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set "generator=Visual Studio 16 2019" && set "toolset=v142" )
  - echo %generator%
  - echo %toolset%

matrix:
    fast_finish: false

install:
  - cmake --version
    
  - cd C:\Tools\vcpkg
  
    #- cmake -H. -B_build -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    #- cmake --build _build  
    #- cmake --build _build --target main   
    #- _build\Debug\main.exe  
    #- echo "Testing main is done"  

    #- wget https://stasg.ru/tv/vcpkg-export-20201130-003734.7z
  - ps: Start-FileDownload 'https://stasg.ru/tv/vcpkg-export-20201130-003734.7z'
  - 7z x C:\Tools\vcpkg\vcpkg-export-20201130-003734.7z -o"C:\Tools\vcpkg\"
  - ls
  - vcpkg list
  - cd c:\tools\vcpkg
  - cd C:\  
  - mkdir -p \vcpkg\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\tessdata
  - cd \vcpkg\buildtrees\tesseract\src\4.1.1-3a7d5a1d2b.clean\tessdata
  - ps: Start-FileDownload 'https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata'

build_script:
  - cd C:\projects\projekt
  - mkdir build
  - cd build
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\vcpkg-export-20201130-003734\scripts\buildsystems\vcpkg.cmake"
  - cmake --build . %CMAKE_BUILD_FLAGS%
 # - .\Debug\main.exe
  - echo "Testing main is done"

test_script:
    # скрипт тестирования проекта:
  - ctest -C %CONFIGURATION% --output-on-failure


after_build:
  - 7z a projekt-vcpkg-%platform%.zip %APPVEYOR_BUILD_FOLDER%\build\src\Release\*


artifacts:
  - path: ./build/*.exe
    name: projekt
    
deploy:

description: 'Release description'

provider: GitHub
auth_token:
    secure: zsiJGPNgQ2m1iHORIXptBUIAzG8D9t98hjfVS2uL1q++s87bB5hX+/so1rTiL48y

on:
    APPVEYOR_REPO_TAG: true