dist: trusty
sudo: require

language: cpp

compiler:
 - gcc
 - clang
cache: ccache
  
    #- TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Release
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-6.0
   - g++-6
   - gcc-6
  
before_install:
   - sudo apt-get install p7zip-rar p7zip-full
   - sudo apt-get install build-essential tar curl zip unzip

##################################################  VPCKG ###########################
script:
  
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  
  - git clone https://github.com/microsoft/vcpkg
  - ./vcpkg/bootstrap-vcpkg.sh
 #- ./vcpkg/vcpkg install sfml tesseract qt5-imageformats
 # - wget -c https://stasg.ru/tv/vcpkg-export-20201130-003734.zip
 # - unzip vcpkg-export-20201130-003734.zip
  - ./vcpkg/vcpkg install sfml 
  - ./vcpkg/vcpkg install qt5-imageformats
  - ./vcpkg/vcpkg install tesseract
  
  - mkdir build && cd build
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=/home/travis/build/s-grig/projekt/vcpkg/scripts/buildsystems/vcpkg.cmake"
  - cmake --build .
  - echo "Main application testing is done"
  #  -DCMAKE_PREFIX_PATH=/usr/local/share/
 # cmake -DTesseract_DIR=/home/travis/build/s-grig/projekt/leptonica-1.80.0/tesseract_s/tesseract/cmake/templates