language: cpp

compiler:
 - gcc
 - clang
env:
    # список переменных окружени€, вли€ющих на матрицу сборки:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Release
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-5.0
   - g++-7
before_install:
   - sudo aptitude install libsfml-dev -y
   - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
   - sudo apt-get update -qq
   - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
   - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake


script:
  - export TESSERACT_VERSION=4.0.0-1
  - export TESSERACT_INSTALL=$HOME/.tesseract
  - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  - wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/$TESSERACT_VERSION/tesseract.tar.xz | tar -C $HOME -xJf -
  - ls
  - cmake --version
  #- cd home/travis/build/s-grig/projekt
  - mkdir sfml
  - cd sfml
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
  - unzip SFML-2.5.1-sources.zip
  - cd SFML-2.5.1
  - sudo apt-get install libx11-dev libgl1-mesa-dev libudev-dev libfreetype6-dev libopenal-dev libflac-dev libvorbis-dev
  - sudo aptitude install x11-xserver-utils
  - sudo apt install libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install xorg-dev -y
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles"
  - sudo make && sudo make install
  - cd ..
  - cd ..

  - mkdir build && cd build
  - cmake -DCMAKE_PREFIX_PATH=/home/travis/build/s-grig/projekt/sfml/SFML-2.5.1 -DCMAKE_INSTALL_PREFIX=/home/travis/build/s-grig/projekt ../
  - cmake --build .
  - echo "Main application testing is done"
 
