language: cpp

compiler:
 - gcc
 - clang

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-5.0
   - g++-7
before_install:
   - git clone https://github.com/microsoft/vcpkg
   - ./vcpkg/bootstrap-vcpkg.sh
   - cd vcpkg
   - vcpkg list
   - ls
   - cd ..

script:
 #- cd hello_world_application
  
  - mkdir build
  - cd build
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - cmake --build .
  - ./_build/main
  - echo "Main application testing is done"
 
