language: cpp

compiler:
 - gcc
 - clang

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-5.0
   - g++-7
before_install:
   - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
   - sudo apt-get update -qq
   - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev  
   - sudo apt-get install libsfml-dev


script:
  - export TESSERACT_VERSION=4.0.0-1
  - export TESSERACT_INSTALL=$HOME/.tesseract
  - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  - wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/$TESSERACT_VERSION/tesseract.tar.xz | tar -C $HOME -xJf -
 
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make
 #- cd hello_world_application
  
  - mkdir build
  - cd build
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - cmake --build .
  - ./_build/main
  - echo "Main application testing is done"
 
