language: cpp

compiler:
 - gcc
 - clang

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-5.0
   - g++-7
before_install:
   - sudo apt-get install libsfml-dev


script:
  - export TESSERACT_VERSION=4.0.0-1
  - export TESSERACT_INSTALL=$HOME/.tesseract
  - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  - wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/$TESSERACT_VERSION/tesseract.tar.xz | tar -C $HOME -xJf -
 
  
 #- cd hello_world_application
  
  
  - cmake -H. -B_build
  - cmake --build _build
  - cmake --build _build --target hello_world
  - ./_build/main
  - echo "Main application testing is done"
 
