language: cpp

compiler:
 - gcc
 - clang
cache: ccache
#env:
   
    #- TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Release
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-5.0
   - g++-7
before_install:
   #- sudo apt-get install libsfml-dev -y
   - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
   - sudo apt-get update -qq
   - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev -y
   - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  
#   - pkg-config --cflags --libs tesseract
   - sudo apt install qt5-default
   - sudo apt-get install libgtk2.0-dev -y
   - sudo apt-get install tree
   
   - sudo apt-get install autoconf automake
    
   - sudo apt-get install libtool-bin libtool-doc
   - sudo apt-get install ca-certificates
   - sudo apt-get install --no-install-recommends asciidoc docbook-xsl xsltproc
   - sudo apt-get install libpango1.0-dev
   - sudo apt-get install pkg-config
   - sudo apt-get install libpng-dev
   - sudo apt-get install libjpeg8-dev
   - sudo apt-get install libtiff5-dev
   - sudo apt-get install zlib1g-dev
   - sudo apt-get install libicu-dev
   - sudo apt-get install libpango1.0-dev
   - sudo apt-get install libcairo2-dev
   
  ################################################################ 
   #- sudo apt install libleptonica-dev
   #- sudo apt-get install tesseract-ocr
   #- sudo apt-get install libtesseract-dev
   #- sudo apt install libopencv-dev -y
   ################################################################
script:
  - echo "$HOME"
  - wget https://github.com/DanBloomberg/leptonica/releases/download/1.80.0/leptonica-1.80.0.tar.gz
  - tar xzvf leptonica-1.80.0.tar.gz
  - cd leptonica-1.80.0
  - mkdir build 
  - cd build
  - cmake ..
  - make 
  
  - cd ..
  - ls
  - cd ..
    
  - git clone https://github.com/tesseract-ocr/tesseract.git
  ##- wget https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz
  - ls /usr/local/lib/cmake
  - ls /usr/local/lib/
  ##- tar xzvf 4.1.1.tar.gz
  - ls
 ## - cd tesseract-4.1.1
  - cd tesseract
 # - ./autogen.sh
 # - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig     
 # - ./configure
  #- LIBLEPT_HEADERSDIR=$HOME/local/include ./configure \
 #- --prefix=$HOME/local/ --with-extra-libraries=$HOME/local/lib
 ### - LIBLEPT_HEADERSDIR=$HOME/local/include ./configure --prefix=$HOME/local/ --with-extra-libraries=$HOME/local/lib
#  - sudo make
 # - sudo make install
#  - sudo ldconfig
 # - cd ..
  - export PKG_CONFIG_PATH = / usr / local / lib / pkgconfig
  - export PKG_CONFIG = / usr / bin / pkg-config
  - sudo cp /usr/local/lib/pkgconfig/lept.pc /usr/lib64/pkgconfig/

Также необходимо убедиться, что эти две переменные определены:


  - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig
  - mkdir build
  - cd build
  - cmake ../
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - cd ..
  - ls
  - tesseract --version
  
  
  
 
  #- export TESSDATA_PREFIX=/home/travis/build/s-grig/projekt/tesseract/
  #- export TESSDATA_PREFIX=/usr/local/share/
  #- export Tesseract_DIR=/home/travis/build/s-grig/projekt/
    
  - ls
  - mkdir sfml
  - cd sfml
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
  - unzip SFML-2.5.1-sources.zip
  - cd SFML-2.5.1
  - sudo apt-get install libx11-dev libgl1-mesa-dev libudev-dev libfreetype6-dev libopenal-dev libflac-dev libvorbis-dev
  - sudo aptitude install x11-xserver-utils -y
  - sudo apt install libavcodec-dev libavformat-dev libswscale-dev -y
  - sudo apt-get install xorg-dev -y
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles"
  - sudo make && sudo make install
  - cd ..
  - ls
  - cd ..
  - ls
  - ls /home
  - echo "$HOME"
  #  "-DCMAKE_PREFIX_PATH=/home/travis/build/s-grig/projekt/tesseract/cmake/"
  - find / -name  "*onfig.cmake" -print 2>/dev/null
  - find  / -name "TesseractConfig*" -print 2>/dev/null
  ##- tree
  ##- tree -P '*esseract*' --prune
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - cmake --build .  --config release
  - echo "Main application testing is done"
  #  -DCMAKE_PREFIX_PATH=/usr/local/share/
  # cmake -DTesseract_DIR=/home/travis/build/s-grig/projekt/leptonica-1.80.0/tesseract_s/tesseract/cmake/templates
  #- cmake .. "-DCMAKE_PREFIX_PATH=/home/travis/build/s-grig/projekt/tesseract/cmake/templates/"
 # "-DCMAKE_PREFIX_PATH=/home/travis/build/s-grig/projekt/tesseract/"
  #cmake -Draspicam_DIR=<dir>
  #"-DCMAKE_PREFIX_PATH=/usr/local/lib/cmake