language: cpp

compiler:
 - gcc
 - clang
#env:
    # список переменных окружени€, вли€ющих на матрицу сборки:
    #- TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    #- TARGET_CPU=x86 BUILD_CONFIGURATION=Release
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-5.0
  packages:
   - cmake
   - cmake-data
   - clang-5.0
   - g++-7
before_install:
   #- sudo apt-get install libsfml-dev -y
   - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
   - sudo apt-get update -qq
   - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev -y
   - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
   #- sudo apt-get install tesseract-ocr
   - sudo apt install libleptonica-dev
   - sudo apt-get install libtesseract-dev
   - sudo apt install libopencv-dev -y
#   - pkg-config --cflags --libs tesseract
   - sudo apt install qt5-default


script:
  - 
  #- export TESSERACT_VERSION=4.0.0-1
  #- export TESSERACT_INSTALL=$HOME/.tesseract
  #- export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  #- export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  #- export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  #- wget -O - https://github.com/nijel/tesseract-ocr-build/releases/download/$TESSERACT_VERSION/tesseract.tar.xz | tar -C $HOME -xJf -
  - ls
  - qmake --version
  - cmake --version
  
 # - git clone https://github.com/microsoft/vcpkg
 #- cd vcpkg
 # - wget https://stasg.ru/tv/vcpkg-export-20201130-003734.zip
 # - unzip vcpkg-export-20201130-003734.zip

 # - ./vcpkg/bootstrap-vcpkg.sh
 # - cd vcpkg 
 # - ./vcpkg list
 # - ./vcpkg install sfml tesseract 
 # - ./vcpkg install qt5-imageformats
 # - ./vcpkg list
#  - cd ..

  #- cd home/travis/build/s-grig/projekt
  - mkdir sfml
  - cd sfml
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
  - unzip SFML-2.5.1-sources.zip
  - cd SFML-2.5.1
  - sudo apt-get install libx11-dev libgl1-mesa-dev libudev-dev libfreetype6-dev libopenal-dev libflac-dev libvorbis-dev
  - sudo aptitude install x11-xserver-utils -y
  - sudo apt install libavcodec-dev libavformat-dev libswscale-dev -y
  - sudo apt-get install xorg-dev -y
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles"
  - sudo make && sudo make install
  - cd ..
  - ls
  - cd ..
  - ls
  - mkdir -p tesseract_s && cd tesseract_s
  - git clone https://github.com/tesseract-ocr/tesseract.git
  - cd tesseract
  - ./autogen.sh
  - autoreconf -i
  - ./configure
  - sudo make && sudo make install
  - sudo ldconfig
  - cd ..
  - cd ..
  - tesseract --version

  - mkdir build && cd build
  - cmake ..
  #- cmake .. "-DCMAKE_TOOLCHAIN_FILE=/home/travis/build/s-grig/projekt/vcpkg/vcpkg-export-20201130-003734/scripts/buildsystems/vcpkg.cmake"
  #- cmake .. "-DCMAKE_PREFIX_PATH=/home/travis/build/s-grig/projekt/sfml/SFML-2.5.1 -DCMAKE_INSTALL_PREFIX=/home/travis/build/s-grig/projekt ../"
  - cmake --build .
  - echo "Main application testing is done"
 
